### ISSUE TITLE
App icon not available in API response

### ISSUE THREAD

**Issue by cball** [zendesk/sunshine-conversations-javascript#130]
I'm currently integrating Smooch into an app, and I have a case where I need to display the Smooch app icon on the page once the user signs up. Is it possible to get this exposed via the `apps.get` or `apps.list` endpoints?

For now, I could add a custom metadata field that points to a specific image but it would be great to not have to manage that in two places.

**Comment by mspensieri** [comment]
Hi @cball, you're right that it's not currently possible to manage or access the app icon via the API. I've filed this as a feature request with the product team, but for now you would have to go with your proposed workaround
