### ISSUE TITLE
Please tell me how to get the appId and conversationId 

### ISSUE THREAD

**Issue by newboom233** [zendesk/sunshine-conversations-javascript#143]
String appId = "5d8cff3cd55b040010928b5b"; // String | Identifies the app.
String conversationId = "029c31f25a21b47effd7be90"; // String | Identifies the conversation.

Brother, please help me how to get these two IDs and what API should I use to get them?

**Comment by UlyssesDB** [comment]
Please reach out to the Sunshine Conversations support team for help with your request, see:
- https://www.zendesk.com/platform/conversations/
and
- https://docs.smooch.io/guide/
