### ISSUE TITLE
 security issues: dependencies of smooch-core

### ISSUE THREAD

**Issue by ChannyAzar** [zendesk/sunshine-conversations-javascript#150]
According to the npm audit security report, there are several security issues caused by modules that are dependencies of smooch-core. 

In the latest version of smooch-core, the following versions are present: 

"jsonwebtoken": "5.4.1", 
"node-fetch": "1.7.2" 

where they should be at least:

"jsonwebtoken": "9.0.0", 
"node-fetch": "2.6.7" 

Can you please update package.json with the versions that align with the security patches that have been made?

Attached is a screenshot with part of the report results.
![image (28)](https://github.com/user-attachments/assets/1f13bb0b-fc08-46a5-a235-acf66cbee8a0)

**Comment by rodgarciab** [comment]
Updates done. This repository is a legacy version, and is not under maintenance. Please migrate your features to use our API v1 or v2
