### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by philcockfield** [zendesk/sunshine-conversations-javascript#81]
It would be nice if we could have TypeScript definitions for your core library API?
Thanks.

**Comment by patrixr** [comment]
Hi,

I'm (very) late on this but thought someone might find this useful:

I've generated some types myself for this project here: https://github.com/patrixr/types-sunshine-conversations-client

I'm currently including them in my project as such:

```jsonc
{
  // ...
  "devDependencies": {
    "@types/sunshine-conversations-client": "git://github.com/patrixr/types-sunshine-conversations-client.git#master",
  }
}
```

If anyone is looking to generate their own, you can use the following command line (could also be useful for other js projects)

```bash
# 
npx -p typescript tsc <sunshineSourceFolder>/**/*.js --declaration --allowJs --emitDeclarationOnly --outDir types-sunshine-conversations-javascript
```

Hope this helps :)

**Comment by DataWearsAHood** [comment]
Thanks @patrixr !

@philcockfield
If you're still interested in native support for such a feature, let us know and I can pass your feedback to the product team for consideration.
